baseurl = "http://duckpuppy.com/"
title = "Random Inconsequential Thoughts"
copyright = "Copyright (c) 2017, all rights reserved"
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = "UA-26376927-1"
disqusShortname = "duckpuppy"

SectionPagesMenu = "main"

pygmentsStyle = "native"
pygmentsCodeFences = true

[author]
  name = "DuckPuppy"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "duckpuppy"
  gitlab = "duckpuppy"
  twitter = "duckpuppy"
  email = "paikens@gmail.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
