title = "Random Inconsequential Thoughts"
baseURL = "http://duckpuppy.com"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "UA-26376927-1"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "duckpuppy"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "favicon.ico" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = ["js/mermaid.min.js"]

  # Description and meta data for the search engines
  author = "Patrick Aikens"
  description = "Random Inconsequential Thoughts"
  keywords = "blog,personal"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "BD7H7DDIHZ"
  algolia_apiKey    = "c98018df99d0f516ec0744bceddec327"
  algolia_indexName = "duckpuppy_com"
    # Set this option to false if you want to search within all articles in all languages at once
    algolia_currentLanguageOnly = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Tech, Pop Culture, Gaming, and other Geekery"

    # if you want to use gravatar for the header image
    gravatarEMail = "paikens@gmail.com"

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = true

    # credits line configuration
    copyrightBy = "by Patrick Aikens"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://duckpuppy.com"
    creditsText = "Random Inconsequential Thoughts"
    creditsUrl = "https://github.com/duckpuppy/blog"

  # social media profile urls for the footer links
  showSocialMedia = true
  facebook   = "https://www.facebook.com/duckpuppy"
  twitter    = "https://twitter.com/duckpuppy"
  googleplus = ""
  pinterest  = ""
  instagram  = "https://www.instagram.com/duckpuppy"
  tumblr     = ""
  youtube    = "https://www.youtube.com/duckpuppy"
  vimeo      = ""
  github     = "https://github.com/duckpuppy"
  gitlab     = "https://gitlab.com/duckpuppy"
  bitbucket  = "https://bitbucket.org/duckpuppy"
  steam      = "https://steamcommunity.com/id/duckpuppy"
  twitch     = "https://twitch.tv/duckpuppy"

# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
# [Languages]
#   [Languages.en]
#     weight = 1
#   [Languages.de]
#     weight = 2
#     title = "Mein cooler neuer Blog"
#     subtitle = "Hallo Welt! Dies ist der epischste Untertitel aller Zeiten."

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
