version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.45
    steps:
      - checkout
      - run:
          name: "Check out submodules"
          command: |
            git submodule sync --recursive
            git submodule update --init --recursive
      - run:
          name: "Check out website"
          command: |
            git clone git@github.com:duckpuppy/duckpuppy.github.io public
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          name: "Deploy to GH Pages"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email "$GH_EMAIL" > /dev/nul 2>&1
              git config --global user.name "$GH_NAME" > /dev/nul 2>&1
              cd public && git add --all && git commit -m "Publishing to gh-pages" && git push || exit 0
            fi
